### PR TITLE
Fix/llhls query

### LINKED ISSUE #1198: LLHLS - playlist loader, querystring breaks uri
I think below line will break loading of playlist if uri already contain a "?".
https://github.com/videojs/http-streaming/blob/81600194030c22c283892e796d71700820478891/src/playlist-loader.js#L74

For me it ends up trying to load a playlist containing double "?" in uri, example below:
https://manifes.fastly.example.com/rendition.m3u8?cdn=fastly&expires=1653133440&live=1&skid=default&signature=ABC?_HLS_msn=8&_HLS_part=0

### PR DESCRIPTION
**Pull request by brandonocasey**
## Description
Fixes #1198

### CODE REVIEW

File: test/loader-common.js [hunk 1]
```diff
@@ -849,11 +849,12 @@ export const LoaderCommonFactory = ({
           this.clock.tick(1);
           return Promise.resolve();
         }).then(() => new Promise((resolve, reject) => {
-          loader.on('playlistupdate', () => {
-            this.clock.tick(1);
-            resolve();
-          });
           loader.on('trackinfo', () => {
+            loader.on('playlistupdate', () => {
```
Comment (brandonocasey) [inline test/loader-common.js:853]: Fixes the race condition that currently causes ie 11 to fail

File: src/playlist-loader.js [hunk 2]
```diff
@@ -62,19 +64,29 @@ const addLLHLSQueryDirectives = (uri, media) => {
...
   }
 
-  query.forEach(function(str, i) {
-    const symbol = i === 0 ? '?' : '&';
+  if (Object.keys(parameters).length) {
+    const parsedUri = new window.URL(uri);
 
-    uri += `${symbol}${str}`;
-  });
+    ['_HLS_skip', '_HLS_msn', '_HLS_part'].forEach(function(name) {
```
Comment (brandonocasey) [inline src/playlist-loader.js:80]: I wanted to make sure that we keep the parameters in an expected order of `skip`, `msn`, and `part` as it makes reading the urls much easier.

**Review by gkatsev — APPROVED** [review]
I also tested it and it works.
