### PR TITLE
fix: race condition preventing qualityLevels from being populating

### LINKED ISSUE #677: Qualities not loading and addqualitylevel event not triggered
## Description
Hello,
If i open the player, in a new tab WITHOUT FOCUSING IT (middle mouse button open for example), and let some time pass (so all javascript may run), the quality levels are not loaded and addqualitylevel event is not even triggered... if you do the same but focusing the window, all runs good.

## Steps to reproduce

1. Open a video page with m3u8 source on a new tab
2. Wait a couple of seconds
3. Go see it (no qualities loaded)

### Expected
Qualities Loaded

### videojs-http-streaming version
videojs-http-streaming 1.9.3

### videojs version
video.js 7.6.5 (im sure that this happens since 7.1.0 or older)

### Browsers
Only tested with Chrome

### Platforms
Only tested with windows 10

### Other Plugins
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

### PR DESCRIPTION
**Pull request by brandonocasey**
## Description
Quality levels is not being populated due to a race condition where the tech is not ready until after we have fired `selectedintialmedia`. You can get this to happen by in chrome by loading the tab in the background for 10s or by using a slow browser like ie 11, where it will happen in the main tab.

## Steps to reproduce
1. Open `index.html`
2. Open the link to `Stats` in a new page, and wait 10s before switching to that tab.
3. Note that the `qualityLevels` do not show up on the page, and `player.qualityLevels().levels_` is a 0 length array
4. Note that `player.representations()` has the correct representations in the returned array. 
5. Note that the `qualityLevels` buttons do not show up on the page.

## Specific Changes proposed
1. The first commit deploys the stats page, and fixes a bug with the stats page. That allows this bug to be tested before the fix.  
2. The second commit remove the tech ready wrapper around `this.setupQualityLevels_()`

## Testing
1. Open the [netlify deploy from #708](https://deploy-preview-708--videojs-http-streaming.netlify.com/) and follow the steps to reproduce.
2. Open [netlify deploy for this pull request](https://deploy-preview-707--videojs-http-streaming.netlify.com/) and follow the steps to reproduce, noting that steps 3, 4, and 5 are no longer an issue.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] Reviewed by Two Core Contributors

Closes #708
Fixes #677

### CODE REVIEW

File: scripts/netlify.js [hunk 1]
```diff
@@ -1,12 +1,14 @@
...
-const fs = require('fs');
-
-const vjs = 'node_modules/video.js/dist/alt/video.core.js';
-const vjsCss = 'node_modules/video.js/dist/video-js.css';
-const eme = 'node_modules/videojs-contrib-eme/dist/videojs-contrib-eme.js';
 const deployDir = 'deploy';
-const files = [vjs, vjsCss, eme];
+
+const files = [
+  'node_modules/video.js/dist/video-js.css',
```
Comment (brandonocasey) [inline scripts/netlify.js]: naming files what getting a bit absurd in here

File: src/rendition-mixin.js [hunk 2]
```diff
@@ -92,6 +92,9 @@ let renditionSelectionMixin = function(hlsHandler) {
 
   // Add a single API-specific function to the HlsHandler instance
   hlsHandler.representations = () => {
+    if (!playlists || !playlists.master || !playlists.master.playlists) {
```
Comment (brandonocasey) [inline src/rendition-mixin.js]: We should probably return an empty array if we don't have playlists yet, Right now we will just throw an error and some of the tests where failing due to this.

File: src/videojs-http-streaming.js [hunk 3]
```diff
@@ -737,17 +737,21 @@ class HlsHandler extends Component {
   setupQualityLevels_() {
     let player = videojs.players[this.tech_.options_.playerId];
 
-    if (player && player.qualityLevels) {
-      this.qualityLevels_ = player.qualityLevels();
+    // if there isn't a player or there isn't a qualityLevels plugin
+    // or qualityLevels_ listeners have already been setup, do nothing.
+    if (!player || !player.qualityLevels || this.qualityLevels_) {
```
Comment (brandonocasey) [inline src/videojs-http-streaming.js]: Only setup quality levels listeners once, the rest of the code is the same except we return early instead of adding the logic in an `if` scope.

File: utils/stats/index.html [hunk 4]
```diff
@@ -20,7 +20,7 @@
 
   <!-- player stats visualization -->
   <link href="stats.css" rel="stylesheet">
-  <script src="/node_modules/d3/d3.min.js"></script>
+  <script src="../../node_modules/d3/d3.min.js"></script>
```
Comment (brandonocasey) [inline utils/stats/index.html]: have to use local paths to get it to work on netlify.

File: utils/stats/index.html [hunk 5]
```diff
@@ -345,25 +345,23 @@ <h3>Timed Metadata</h3>
         videojs.Hls.displayStats(document.querySelector('.switching-stats'), player);
         videojs.Hls.displayCues(document.querySelector('.segment-timeline'), player);
 
-        player.ready(function() {
-          var qualityLevels = player.qualityLevels();
+        var qualityLevels = player.qualityLevels();
```
Comment (brandonocasey) [inline utils/stats/index.html]: quality levels can exist before tech/player ready

File: test/videojs-http-streaming.test.js [hunk 6]
```diff
@@ -3094,8 +3094,7 @@ QUnit.test('passes useCueTags hls option to master playlist controller', functio
   videojs.options.hls = origHlsOptions;
 });
 
-// TODO: This test fails intermittently. Turn on when fixed to always pass.
-QUnit.skip('populates quality levels list when available', function(assert) {
+QUnit.test('populates quality levels list when available', function(assert) {
```
Comment (brandonocasey) [inline test/videojs-http-streaming.test.js]: This test was previously skipped because of intermittent failures. I think fixing this bug fixes the test.

File: scripts/netlify.js [hunk 7]
```diff
@@ -20,5 +22,5 @@ files
 
 // copy over files, dist, and html files
```
[the remark this answers is not in the document]
Comment (brandonocasey) [reply scripts/netlify.js]: updated the comment to make it more relevant

**Comment by gkatsev** [comment]
This fixes https://github.com/videojs/http-streaming/issues/677 as well.

**Comment by gkatsev** [comment]
@brandonocasey can you make this change against master as well? Thanks!
