### PR TITLE
fix: abort all loaders on earlyabort

### LINKED ISSUE #964: experimentalBufferBasedABR (and maybe regular ABR too): fixup ABR when no progress events from XHR
When we get really bad network for a long time and download of gear5 fails, we end up running out of buffer because our downswitch didn't run because last check happened when we had plenty of buffer and we no longer earlyabort

### PR DESCRIPTION
**Pull request by brandonocasey**
During low bandwidth situations continuing to download any segments over the video/audio segment is ill-advised as we need to get the buffer filled again ASAP. So when we get an early abort we have to abort all segment loaders to make way for the new playlist that is about to load, so that it can have priority.

Fixes #964

### CODE REVIEW

File: src/config.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ export default {
   BUFFER_LOW_WATER_LINE: 0,
   MAX_BUFFER_LOW_WATER_LINE: 30,
 
-  // TODO: Remove this when useBufferWaterLines is removed
+  // TODO: Remove this when experimentalBufferBasedABR is removed
```
Comment (brandonocasey) [inline src/config.js:15]: so that we can remove this comments/code when we need to later on.

**Review by gkatsev — DISMISSED** [review]

**Comment by gkatsev** [comment]
Is this something that we think is still necessary? Or could just be closed because we're not doing any earlyabort in the new ABR stuff?

File: src/master-playlist-controller.js [hunk 2]
```diff
@@ -617,11 +619,24 @@ export class MasterPlaylistController extends videojs.EventTarget {
...
+        abortSeconds = Config.EXPERIMENTAL_MAX_BUFFER_LOW_WATER_LINE;
       }
+
+      this.mainSegmentLoader_.abort();
+      if (this.mediaTypes_.AUDIO.activePlaylistLoader) {
+        this.audioSegmentLoader_.abort();
+      }
+      if (this.mediaTypes_.SUBTITLES.activePlaylistLoader) {
+        this.subtitleSegmentLoader_.abort();
+      }
```
Comment (gesinger) [inline src/master-playlist-controller.js:634]: Should this use `delegateLoaders_`?

File: src/master-playlist-controller.js [hunk 3]
```diff
@@ -599,6 +599,8 @@ export class MasterPlaylistController extends videojs.EventTarget {
     });
 
     this.mainSegmentLoader_.on('earlyabort', (event) => {
+      let abortSeconds = ABORT_EARLY_BLACKLIST_SECONDS;
```
Comment (gesinger) [inline src/master-playlist-controller.js:602]: Minor, but this may make more sense as `blacklistSeconds`

**Review by gesinger — APPROVED** [review]
