### PR TITLE
fix: fix replay functionality

### LINKED ISSUE #201: Replay is not working
## Description
The replay functionality seems broken, when attempting to replay the player freezes and spins.

## Sources
This can be reproduced with bipbop in the demo page

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play and seek to the end of the video
2. Click the replay button to restart the video

### Expected
The player should replay the video from the start

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here: __no errors__
You will notice that the buffered range is still the end of the video

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.2.4

### videojs version
what version of videojs does this occur with?
video.js 7.1.0

### Browsers
what browsers are affected? please include browser and version for each
*Only tried Chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Only tried Mac

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* none

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* none

History:
```
[
  ["WARN:", "A plugin named \"reloadSourceOnError\" already exists. You may want to avoid re-registering plugins!"],
  ["DEBUG:", "VHS:", "PlaybackWatcher >", "initialize"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "playlist update [null => 2]"],
  ["DEBUG:", "VHS:", "SyncController >", "syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]"],
  ["DEBUG:", "VHS:", "MPC >", "seekable updated [0 => 1800.0118999999966]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "playlist update [2 => 2]"],
  ["DEBUG:", "VHS:", "SyncController >", "syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]"],
  ["DEBUG:", "VHS:", "MPC >", "seekable updated [0 => 1800.0118999999966]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "live window shift [0]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "INIT -> READY"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "created SourceBuffer"],
  ["DEBUG:", "VHS:", "SyncController >", "syncPoint for [time: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "READY -> WAITING"],
  ["DEBUG:", "VHS:", "SyncController >", "time mapping for timeline 0: [time: 0] [mapping: -10]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "WAITING -> APPENDING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "appending [0] of [0, 181] from playlist [2] [0 => 9.943277777777777] in timeline [0]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered [0 => 9.976643]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "APPENDING -> READY"],
  ["DEBUG:", "VHS:", "SyncController >", "syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]"],
  ["DEBUG:", "VHS:", "MPC >", "seekable updated [0 => 1799.9785777777743]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "READY -> WAITING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "WAITING -> APPENDING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "appending [1] of [0, 181] from playlist [2] [9.976644444444446 => 19.919922222222223] in timeline [0]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered [0 => 19.953288]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "APPENDING -> READY"],
  ["DEBUG:", "VHS:", "SyncController >", "syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]"],
  ["DEBUG:", "VHS:", "MPC >", "seekable updated [0 => 1800.0119222222188]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "READY -> WAITING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "WAITING -> APPENDING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "appending [2] of [0, 181] from playlist [2] [19.95328888888889 => 29.896566666666665] in timeline [0]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered [0 => 29.907255]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "APPENDING -> READY"],
  ["DEBUG:", "VHS:", "SyncController >", "syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]"],
  ["DEBUG:", "VHS:", "MPC >", "seekable updated [0 => 1799.9785666666633]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "READY -> WAITING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "WAITING -> APPENDING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "appending [3] of [0, 181] from playlist [2] [29.92993333333333 => 39.87321111111111] in timeline [0]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered [0 => 39.891835]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "APPENDING -> READY"],
  ["DEBUG:", "VHS:", "SyncController >", "syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]"],
  ["DEBUG:", "VHS:", "MPC >", "seekable updated [0 => 1800.0119111111078]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "READY -> WAITING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "WAITING -> APPENDING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "appending [4] of [0, 181] from playlist [2] [39.90657777777778 => 49.84984444444444] in timeline [0]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered [0 => 49.876416]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "APPENDING -> READY"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "remove [0 => 1800.0118999999966]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered []"],
  ["DEBUG:", "VHS:", "SyncController >", "syncPoint for [time: 1786.375446] chosen with strategy [Segment]: [time:39.90657777777778, segmentIndex:4]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "READY -> WAITING"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "remove [0 => 1756.375446]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered []"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "WAITING -> APPENDING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "appending [178] of [0, 181] from playlist [2] [1775.8425111111112 => 1785.7857888888889] in timeline [0]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered [1775.862131 => 1785.800271]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "APPENDING -> READY"],
  ["DEBUG:", "VHS:", "SyncController >", "syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]"],
  ["DEBUG:", "VHS:", "MPC >", "seekable updated [0 => 1799.944188888889]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "READY -> WAITING"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "remove [0 => 1756.375446]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered [1775.862131 => 1785.800271]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "WAITING -> APPENDING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "appending [179] of [0, 181] from playlist [2] [1785.8191555555557 => 1795.7624333333333] in timeline [0]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered [1775.862131 => 1795.784806]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "APPENDING -> READY"],
  ["DEBUG:", "VHS:", "SyncController >", "syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]"],
  ["DEBUG:", "VHS:", "MPC >", "seekable updated [0 => 1799.9775333333332]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "READY -> WAITING"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "remove [0 => 1756.375446]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered [1775.862131 => 1795.784806]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "WAITING -> APPENDING"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "appending [180] of [0, 181] from playlist [2] [1795.7958 => 1799.9666333333332] in timeline [0]"],
  ["DEBUG:", "VHS:", "SourceUpdater[main][video/mp2t; codecs=\"avc1.4d401f, mp4a.40.2\"] >", "buffered [1775.862131 => 1799.999999]"],
  ["DEBUG:", "VHS:", "SegmentLoader[main] >", "APPENDING -> READY"],
  ["DEBUG:", "VHS:", "SyncController >", "syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]"],
  ["DEBUG:", "VHS:", "MPC >", "seekable updated [0 => 1799.9666333333332]"]
]
```

### PR DESCRIPTION
**Pull request by forbesjo**
## Description
Fixes #201 

## Specific Changes proposed
Replay is broken because VHS is not loading the buffer when the video element seeks on replay. This previously worked because VHS would react to video element seek events. The seek caused by replay does not call `player.currentTime()` so the middleware does not kick in. This adds an additional middleware to call VHS's during play calls. 

Previously the play method of VHS would not go down the ended -> seek to 0 path because the tech would have already seeked to 0 on it's own, then emitted a play event.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [x] If necessary, more likely in a feature request than a bug fix
  - [x] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://jsbin.com/gejugat/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

File: src/middleware-set-current-time.js [hunk 1]
```diff
@@ -12,12 +12,20 @@ videojs.use('*', (player) => {
...
         player.vhs.setCurrentTime(time);
       }
 
       return time;
+    },
+
+    play() {
+      if (player.vhs &&
+          player.currentSource().src === player.vhs.source_.src) {
+        player.vhs.setCurrentTime(player.currentTime());
```
Comment (gesinger) [inline src/middleware-set-current-time.js]: I know this is meant to be a short-term fix, but we should add some comments about what we're doing and why it works for the replay case.

File: test/playback.test.js [hunk 2]
```diff
@@ -59,6 +59,36 @@ QUnit.test('Advanced Bip Bop', function(assert) {
...
+  player.autoplay(true);
+
+  // seek to near the end of the video
+  playFor(player, 1, function() {
+    player.currentTime(player.duration() - 1);
+  });
+
+  player.one('ended', function() {
+    player.one('timeupdate', function() {
+      assert.ok(true, 'played');
```
Comment (gesinger) [inline test/playback.test.js]: It might be worth checking the `currentTime` here.

**Comment by forbesjo** [comment]
Instead of calling VHS's play before the tech's play, I am syncing VHS with the player after play. This is because I had an issue with live streams where the VHS play assumes that the player is in a playing state.

File: src/middleware-set-current-time.js [hunk 3]
```diff
@@ -12,12 +12,23 @@ videojs.use('*', (player) => {
...
+          player.currentSource().src === player.vhs.source_.src) {
         player.vhs.setCurrentTime(time);
       }
 
       return time;
+    },
+
+    // Sync VHS after play requests.
+    // This specifically handles replay where the video element will
+    // seek to 0, skipping the setCurrentTime middleware, then play
```
Comment (ldayananda) [inline src/middleware-set-current-time.js]: technically it plays first, but triggers the play event last

File: src/middleware-set-current-time.js [hunk 4]
```diff
@@ -12,12 +12,23 @@ videojs.use('*', (player) => {
...
+    play() {
+      if (player.vhs &&
+          player.currentSource().src === player.vhs.source_.src) {
+        player.vhs.setCurrentTime(player.currentTime());
```
Comment (ldayananda) [inline src/middleware-set-current-time.js]: I think I would feel better if we specifically handled the case where `player.currentTime() === 0` instead of always doing this

File: test/playback.test.js [hunk 5]
```diff
@@ -59,6 +59,36 @@ QUnit.test('Advanced Bip Bop', function(assert) {
   });
 });
 
+QUnit.test('replay', function(assert) {
+  let done = assert.async();
+
+  assert.expect(2);
+  let player = this.player;
+
+  player.autoplay(true);
```
Comment (ldayananda) [inline test/playback.test.js]: do you have to autoplay? Seems like this would be annoying to manage with autoplay restrictions

File: src/middleware-set-current-time.js (hunk 3 above)
Comment (forbesjo) [reply src/middleware-set-current-time.js]: I'll clarify

File: test/playback.test.js (hunk 5 above)
Comment (forbesjo) [reply test/playback.test.js]: This is to simplify the tests and not have to wait for loadstart before playing. Autoplay restrictions aren't a problem because the player is muted

Comment (forbesjo) [reply test/playback.test.js]: I could remove the autoplay setting from all the tests and just create the player with autoplay on

**Comment by gesinger** [comment]
Tested in Chrome, Firefox, and IE11 (on a Windows VM).

**Comment by gkatsev** [comment]
The middleware file probably should be renamed now 🙂
